version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: fsp_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
  redis:
    image: redis:7.2
    container_name: fsp_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
volumes:
  mongo_data: