name: 🚀 FSP Navigator Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  fix-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Fix All Issues
      run: |
        cd frontend
        cat > package.json << 'EOF'
        {
          "name": "fsp-navigator",
          "version": "1.0.0",
          "dependencies": {
            "react": "^18.2.0",
            "react-dom": "^18.2.0",
            "react-scripts": "5.0.1"
          },
          "scripts": {
            "build": "SKIP_PREFLIGHT_CHECK=true react-scripts build"
          }
        }
        EOF
        
    - name: Build
      run: |
        cd frontend
        npm install --force
        npm run build
        
    - name: Deploy Ready
      run: echo "✅ Ready for Emergent.sh deployment!"